rvm:
  - 1.9.3

env:
  - ORM=ar

bundler_args: "--without development production profiling"
before_script: "./config/ci/before-travis.sh"
script: "cd test/communitypack_test_app ; bundle exec rake travis"
gemfile: "test/communitypack_test_app/gemfiles/Gemfile"